### ISSUE TITLE
Plugin install error

### ISSUE THREAD

**Issue by wffancy** [ash3D/UEVideoRecorder#15]
@ash3D Hi, bro. I get into some trouble unfortunately while installing the plugin. After successfully compiled the VideoRecorder solution using vs2019 as it indicating its need of v142 toolkit, I copy the UEVideoRecorder folder into the 'Plugins' folder under my own projects. However, I get the following error when I open the UE editor. I am currently using 4.19 version of UE. I have no idea how to deal with this. I would really appreciate your help.
![image](https://user-images.githubusercontent.com/50099204/122217603-25605b00-cee0-11eb-81a6-142dc169950d.png)

**Comment by ash3D** [comment]
@wffancy Hi.
Older UE versions can be incompatible with v142 toolset. Try v141 for VideoRecorder (do not forget also to switch DirectXTex dependency to VS 2017 solution).
Build log should contain detailed info which can help to figure out what goes wrong.

**Comment by wffancy** [comment]
Thanks for your awesome work and help. I finally install the plugin successfully. However, I find the newest version of code can not be compiled correctly under vs2017 in the project though the VideoRecorder itself can pass the compilation. Everything works fine under **UE4.23** using **vs2019** to build the solution. I Hope this can help the following guys who are interersted in this great work.

**Comment by wffancy** [comment]
Well, I tried to use this plugin under ue4.21 and compile it using vs2017 then, and I found this also worked perfectly. Maybe I made some mistakes before but I had forgotten the reason. Sorry for the misleading though, this work is great:)
