### ISSUE TITLE
Compile errors when compiling with #NO_LOGGING (packaging)

### ISSUE THREAD

**Issue by MykonCodes** [ash3D/UEVideoRecorder#6]
In: VideoRecordGameViewportClient.cpp

`#if NO_LOGGING
	if (verbosity == ELogVerbosity::Fatal)
		FError::LowLevelFatal(__FILE__, __LINE__, msgStr.c_str());`

UnrealBuildTool: C:\Build\dev-unstable\Plugins\UEVideoRecorder\Source\UEVideoRecorder\Private\VideoRecordGameViewportClient.cpp(133): error C2653: 'FError': is not a class or namespace name
UnrealBuildTool: C:\Build\dev-unstable\Plugins\UEVideoRecorder\Source\UEVideoRecorder\Private\VideoRecordGameViewportClient.cpp(133): error C3861: 'LowLevelFatal': identifier not found

[Update, that didnt fix it yet]
//Fix: Add #include "ErrorException.h" in VideoRecorderGameViewportClient.cpp

The issue is that FError is wrapped in #if HACK_HEADER_GENERATOR
UE4 explicitly states that end users shouldn't fiddle with that define and only set it in the UBT. I just removed the two lines for now.

**Comment by ash3D** [comment]
@MykonCodes What UE version do you use?

**Comment by MykonCodes** [comment]
@ash3D  4.17.2

**Comment by ash3D** [comment]
@MykonCodes I have updated the plugin, check it out.

**Comment by MykonCodes** [comment]
Cool, thanks Btw working on getting live audio encoding integrated, changing the API quite heavily for that (keeping current functionality), but if you're interested I can send it to you or just upload it to a fork (once it's done).

**Comment by ash3D** [comment]
Audio encoding would be great. There already was interest in this functionality - look at #4 for discussions. You may send pull request when you are done.
